services:
  dizoriza-app:
    build:
      context: .  # Lokasi Dockerfile
      dockerfile: Dockerfile
    container_name: dizoriza-app
    ports:
      - "5000:5000"  # Menghubungkan port Flask di dalam kontainer ke host
    volumes:
      - ./static/uploads:/app/static/uploads  # Untuk file yang di-upload
      - ./static/results:/app/static/results  # Untuk output model
    environment:
      - FLASK_ENV=production  # Ubah ke "development" jika debugging
    restart: unless-stopped
